#!/usr/bin/env bash
# TODO: find a build system
case "$1" in
release)
	cc_args=(-O2)
	;;
debug)
	cc_args=(-Og -g)
	;;
*)
	echo "./build (release|debug)" >&2
	exit 1
	;;
esac

shift
mkdir -p out
cc "${cc_args[@]}" "$@" -lm -lsymengine -Wall -Werror -Wno-error=unused-{{but-set-,}{parameter,variable},const-variable,function,label,local-typedefs,macros,value,variable} src/{main.c,display.c,sim.c,util.c,rk4.c} -o out/dpend
