#!/usr/bin/env bash
# TODO: find a build system
mkdir -p out
gcc_args=(-lm -Wall -Werror -Wno-error=unused-{{but-set-,}{parameter,variable},const-variable,function,label,local-typedefs,macros,value,variable} src/{main.c,display.c,sim.c,util.c} -o out/dpend)
case "$1" in
release)
	gcc -O2 "${gcc_args[@]}"
	;;
debug)
	gcc -Og -g3 "${gcc_args[@]}"
	;;
*)
	echo "./build (release|debug)" >&2
	;;
esac
